### ISSUE TITLE
見た目で気になった点

### ISSUE THREAD

**Issue by pitang1965** [XNCOAISN/qin-team-portfolio#15]
見た目で気になったの以下だけです。

1. ホームページのBlog等のセクションの上の余白が多め(Aboutページ等は問題ない）
2. （細かい話）ContactページのYour message が Your Message になっている
3. （細かい話）BlogページのLoaderの色がデフォルト（Figmaはred）

**Comment by XNCOAISN** [comment]
@pitang1965 
修正しました
